# Generated by Django 3.1.7 on 2021-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('posted_by', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('blog_image', models.ImageField(upload_to='blog')),
                ('blog_date', models.DateField()),
            ],
        ),
    ]
